/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.assign1_temp;

public class Queries {
    public String ID;
    public String paramType;
    public String sql_query;

    public Queries(String ID, String paramType, String sql_query){
        this.ID = ID;
        this.paramType = paramType;
        this.sql_query = sql_query;
    }

//    @Override
//    public String toString() {
//        return "<" + ID + ", " + paramType + ", " + sql_query + ">\n";
//    }
}
